name: clearex
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12,<3.13
  - pip
  - cython
  - dask=2026.1.1
  - dask-image
  - dask-jobqueue
  - distributed=2026.1.1
  - h5py
  - jupyterlab
  - matplotlib
  - numpy
  - opencv
  - pandas
  - pyarrow
  - pytest
  - pywavelets
  - seaborn
  - scikit-image
  - scipy
  - simpleitk
  - tifffile=2025.10.16
  - zarr=3.1.5
  - pip:
      - antspyx
      - neuroglancer (>=2.40.1,<3.0.0)
      - PyQt6>=6.7
      - -e .[viewer]
